AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation template for millisecond application.It is observed by aoutoscalling group.

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP For ALB #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          From port: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH from ALB #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          From port: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          From port: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          SourceSecurityGroupId:  !GetAtt  ALBSecurityGroup.GroupId
  WebServerlaunchtemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: 0742b4e673072066f 
        InstanceInitiatedShutdownBehavior: String
        InstanceMarketOptions: 
          InstanceMarketOptions
        InstanceType: String
        KernelId: String
        KeyName: String
        LicenseSpecifications: 
          - LicenseSpecification
        MetadataOptions: 
          MetadataOptions
        Monitoring: 
          Monitoring
        NetworkInterfaces: 
          - NetworkInterface
        Placement: 
          Placement
        RamDiskId: String
        SecurityGroupIds: 
          - String
        SecurityGroups: 
          - String
        TagSpecifications: 
          - TagSpecification
        UserData: String
            LaunchTemplateName: String
            TagSpecifications:
              - LaunchTemplateTagSpecification        
Outputs: